development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: redis://redistogo:f091bf5f4fbb8b7243607a7ad239347b@pike.redistogo.com:9411/
  channel_prefix: project_0_production
